[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "functions/"

[dev]
command = "npm run dev"
targetPort = 3000
autoLaunch = false


[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
